import type { Card } from "@/types/CardTypes";
export const searchEngineData: Card[] = [
  {
    id: 1,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.reddit.com/&size=32",
    title: "Reddit",
    path: "https://www.reddit.com/",
    des: "Dive into anything. Find communities and discussions on any topic you love.",
  },
  {
    id: 2,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.netflix.com/&size=32",
    title: "Netflix",
    path: "https://www.netflix.com/",
    des: "Watch TV shows and movies anytime, anywhere. Start your free trial today!",
  },
  {
    id: 3,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.amazon.com/&size=32",
    title: "Amazon",
    path: "https://www.amazon.com/",
    des: "Join the conversation! Twitter is the place to find out what's happening in the world right now.",
  },
  {
    id: 4,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.wikipedia.org/&size=32",
    title: "Wikipedia",
    path: "https://www.wikipedia.org/",
    des: "The free encyclopedia that anyone can edit.",
  },
  {
    id: 5,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.linkedin.com/&size=32",
    title: "LinkedIn",
    des: "Join the conversation! Twitter is the place to find out what's happening in the world right now.",
    path: "https://www.linkedin.com/",
  },
  {
    id: 6,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.instagram.com/&size=32",
    title: "Instagram",
    path: "https://www.instagram.com/",
    des: "Create & share photos, stories, & reels with your friends and the world.",
  },
  {
    id: 7,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.twitter.com/&size=32",
    title: "Twitter",
    path: "https://www.twitter.com/",
    des: "Join the conversation! Twitter is the place to find out what's happening in the world right now.",
  },
  {
    id: 8,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.youtube.com/&size=32",
    title: "YouTube",
    path: "https://www.youtube.com/",
    des: "Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.",
  },
  {
    id: 9,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.twitter.com/&size=32",
    title: "Twitter",
    path: "https://www.twitter.com/",
    des: "Join the conversation! Twitter is the place to find out what's happening in the world right now.",
  },
  {
    id: 10,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.instagram.com/&size=32",
    title: "Instagram",
    path: "https://www.instagram.com/",
    des: "Create & share photos, stories, & reels with your friends and the world.",
  },
  {
    id: 11,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.linkedin.com/&size=32",
    title: "LinkedIn",
    path: "https://www.linkedin.com/",
    des: "Connect with professionals, grow your network, and advance your career with LinkedIn.",
  },
  {
    id: 12,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.wikipedia.org/&size=32",
    title: "Wikipedia",
    path: "https://www.wikipedia.org/",
    des: "The free encyclopedia that anyone can edit.",
  },
  {
    id: 13,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.amazon.com/&size=32",
    title: "Amazon",
    path: "https://www.amazon.com/",
    des: "Shop online for electronics, clothing, books, and more at Amazon.",
  },
  {
    id: 14,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732196.png",
    title: "Base64 Encoder/Decoder",
    path: "https://www.base64-image.de/",
    des: "Encode and decode Base64 data easily.",
  },
  {
    id: 15,
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.amazon.com/&size=32",
    title: "Amazon",
    path: "https://www.amazon.com/",
    des: "Shop online for electronics, clothing, books, and more at Amazon.",
  },
  {
    id: 16,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732203.png",
    title: "Currency Converter",
    path: "https://www.xe.com/currencyconverter/",
    des: "Convert currency values in real-time.",
  },
  {
    id: 17,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732215.png",
    title: "IP Address Lookup",
    path: "https://www.whatismyip.com/",
    des: "Find out your public IP address and details.",
  },
  {
    id: 18,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732208.png",
    title: "Barcode Generator",
    path: "https://barcode.tec-it.com/",
    des: "Create various types of barcodes online.",
  },
  {
    id: 19,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732227.png",
    title: "Text to Speech Converter",
    path: "https://ttsmp3.com/",
    des: "Convert written text into spoken words.",
  },
  {
    id: 20,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732228.png",
    title: "Word Counter",
    path: "https://wordcounter.net/",
    des: "Count words and characters in your text.",
  },
];
